### ISSUE TITLE
Cannot find package

### ISSUE THREAD

**Issue by cmptscpeacock** [digitalocean/terraform-provider-sendgrid#1]
Hi,

Cloned the repo, run "make build" but the following errors are shown:

make build
go build -o terraform-provider-sendgrid -v
../go/src/github.com/hashicorp/go-getter/get_s3.go:11:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get_s3.go:12:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/aws/credentials (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get_s3.go:13:2: cannot find package "github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get_s3.go:14:2: cannot find package "github.com/aws/aws-sdk-go/aws/ec2metadata" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get_s3.go:15:2: cannot find package "github.com/aws/aws-sdk-go/aws/session" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/aws/session (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/aws/session (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get_s3.go:16:2: cannot find package "github.com/aws/aws-sdk-go/service/s3" in any of:
        /usr/lib/go-1.10/src/github.com/aws/aws-sdk-go/service/s3 (from $GOROOT)
        /root/go/src/github.com/aws/aws-sdk-go/service/s3 (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/netrc.go:9:2: cannot find package "github.com/bgentry/go-netrc/netrc" in any of:
        /usr/lib/go-1.10/src/github.com/bgentry/go-netrc/netrc (from $GOROOT)
        /root/go/src/github.com/bgentry/go-netrc/netrc (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/get.go:22:2: cannot find package "github.com/hashicorp/go-cleanhttp" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/go-cleanhttp (from $GOROOT)
        /root/go/src/github.com/hashicorp/go-cleanhttp (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/client.go:13:2: cannot find package "github.com/hashicorp/go-safetemp" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/go-safetemp (from $GOROOT)
        /root/go/src/github.com/hashicorp/go-safetemp (from $GOPATH)
../go/src/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go:18:2: no Go files in /root/go/src/github.com/hashicorp/go-uuid
../go/src/github.com/hashicorp/terraform-plugin-sdk/internal/configs/hcl2shim/single_attr_body.go:6:2: cannot find package "github.com/hashicorp/hcl/v2" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2 (from $GOROOT)
        /root/go/src/github.com/hashicorp/hcl/v2 (from $GOPATH)
../go/src/github.com/hashicorp/terraform-plugin-sdk/internal/addrs/module_instance.go:8:2: cannot find package "github.com/hashicorp/hcl/v2/hclsyntax" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOROOT)
        /root/go/src/github.com/hashicorp/hcl/v2/hclsyntax (from $GOPATH)
../go/src/github.com/hashicorp/terraform-plugin-test/config.go:8:2: cannot find package "github.com/hashicorp/terraform-exec/tfinstall" in any of:
        /usr/lib/go-1.10/src/github.com/hashicorp/terraform-exec/tfinstall (from $GOROOT)
        /root/go/src/github.com/hashicorp/terraform-exec/tfinstall (from $GOPATH)
../go/src/github.com/digitalocean/terraform-provider-sendgrid/sendgrid/resource_api_key.go:13:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
        /root/go/src/github.com/pkg/errors (from $GOPATH)
../go/src/github.com/hashicorp/go-getter/decompress_txz.go:8:2: cannot find package "github.com/ulikunitz/xz" in any of:
        /usr/lib/go-1.10/src/github.com/ulikunitz/xz (from $GOROOT)
        /root/go/src/github.com/ulikunitz/xz (from $GOPATH)
../go/src/cloud.google.com/go/internal/trace/trace.go:21:2: cannot find package "go.opencensus.io/trace" in any of:
        /usr/lib/go-1.10/src/go.opencensus.io/trace (from $GOROOT)
        /root/go/src/go.opencensus.io/trace (from $GOPATH)
../go/src/github.com/digitalocean/terraform-provider-sendgrid/sendgrid/resource_subuser.go:18:2: cannot find package "golang.org/x/sync/errgroup" in any of:
        /usr/lib/go-1.10/src/golang.org/x/sync/errgroup (from $GOROOT)
        /root/go/src/golang.org/x/sync/errgroup (from $GOPATH)
../go/src/cloud.google.com/go/internal/annotate.go:20:2: cannot find package "google.golang.org/api/googleapi" in any of:
        /usr/lib/go-1.10/src/google.golang.org/api/googleapi (from $GOROOT)
        /root/go/src/google.golang.org/api/googleapi (from $GOPATH)
../go/src/cloud.google.com/go/storage/bucket.go:27:2: cannot find package "google.golang.org/api/iterator" in any of:
        /usr/lib/go-1.10/src/google.golang.org/api/iterator (from $GOROOT)
        /root/go/src/google.golang.org/api/iterator (from $GOPATH)
../go/src/cloud.google.com/go/storage/storage.go:45:2: cannot find package "google.golang.org/api/option" in any of:
        /usr/lib/go-1.10/src/google.golang.org/api/option (from $GOROOT)
        /root/go/src/google.golang.org/api/option (from $GOPATH)
../go/src/cloud.google.com/go/storage/acl.go:24:2: cannot find package "google.golang.org/api/storage/v1" in any of:
        /usr/lib/go-1.10/src/google.golang.org/api/storage/v1 (from $GOROOT)
        /root/go/src/google.golang.org/api/storage/v1 (from $GOPATH)
../go/src/cloud.google.com/go/storage/storage.go:47:2: cannot find package "google.golang.org/api/transport/http" in any of:
        /usr/lib/go-1.10/src/google.golang.org/api/transport/http (from $GOROOT)
        /root/go/src/google.golang.org/api/transport/http (from $GOPATH)
Makefile:15: recipe for target 'terraform-provider-sendgrid' failed
make: *** [terraform-provider-sendgrid] Error 1

**Comment by jrm780** [comment]
Hi @cmptscpeacock,

Apologies for the delayed response. It looks like you're using Go version 1.10, which isn't compatible with [Go Modules](https://blog.golang.org/using-go-modules). I recommend updating to the latest version of Golang, or, if that is not feasible, at least 1.13.

Please let me know if this resolves your issue.
